[package]
name = "corrode-assets"
version.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
rust-embed = "^8.9.0"

[build-dependencies]
prettyplease = "0.2.37"
quote = "^1.0.42"
rust-embed = "^8.9.0"
syn = "2.0.110"
